>>> pprint(device.get_interface_description('genie'), indent=4) 
{   'interfaces': {   'Ap1/0/1': {   'description': '',
                                     'protocol': 'up',
                                     'status': 'up'},
                      'Ap2/0/1': {   'description': '',
                                     'protocol': 'up',
                                     'status': 'up'},
                      'Ap3/0/1': {   'description': '',
                                     'protocol': 'up',
                                     'status': 'up'},
                      'FortyGigabitEthernet1/1/1': {   'description': '',
                                                       'protocol': 'down',
                                                       'status': 'down'},
                      'FortyGigabitEthernet1/1/2': {   'description': '',
                                                       'protocol': 'down',
                                                       'status': 'down'},
                      'FortyGigabitEthernet2/1/1': {   'description': '',
                                                       'protocol': 'down',
                                                       'status': 'down'},
                      'FortyGigabitEthernet2/1/2': {   'description': '',
                                                       'protocol': 'down',
                                                       'status': 'down'},
                      'FortyGigabitEthernet3/1/1': {   'description': '',
                                                       'protocol': 'down',
                                                       'status': 'down'},
                      'FortyGigabitEthernet3/1/2': {   'description': '',
                                                       'protocol': 'down',
                                                       'status': 'down'},
                      'GigabitEthernet0/0': {   'description': '',
                                                'protocol': 'down',
                                                'status': 'admin down'},
                      'GigabitEthernet1/0/1': {   'description': 'VCE1_LAN3',
                                                  'protocol': 'up',
                                                  'status': 'up'},
                      'GigabitEthernet1/0/10': {   'description': 'DEMARC_WANA',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet1/0/11': {   'description': 'WAP',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet1/0/12': {   'description': 'WAP',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet1/0/13': {   'description': 'WAP',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet1/0/14': {   'description': 'WAP',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet1/0/15': {   'description': 'WAP',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet1/0/16': {   'description': 'WAP',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet1/0/17': {   'description': 'WAP',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet1/0/18': {   'description': 'WAP',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet1/0/19': {   'description': 'WAP',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet1/0/2': {   'description': '//RESERVED_VCE//',
                                                  'protocol': 'down',
                                                  'status': 'admin down'},
                      'GigabitEthernet1/0/20': {   'description': 'WAP',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet1/0/21': {   'description': 'CE_DE',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet1/0/22': {   'description': 'CE_DE',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet1/0/23': {   'description': 'PoE '
                                                                  'Initiatives',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet1/0/24': {   'description': 'NVR '
                                                                  'Security '
                                                                  'Camera',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet1/0/25': {   'description': 'VSAM',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet1/0/26': {   'description': 'BoH '
                                                                  'Breakroom '
                                                                  'iMac',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet1/0/27': {   'description': 'mPOS Wired '
                                                                  'Printer',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet1/0/28': {   'description': 'mPOS Wired '
                                                                  'Printer',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet1/0/29': {   'description': 'Cash Drawer',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet1/0/3': {   'description': 'VCE1_GE1_WANA',
                                                  'protocol': 'up',
                                                  'status': 'up'},
                      'GigabitEthernet1/0/30': {   'description': 'Cash Drawer',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet1/0/31': {   'description': 'Cash Drawer',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet1/0/32': {   'description': 'BOH',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet1/0/33': {   'description': 'BOH',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet1/0/34': {   'description': 'BOH',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet1/0/35': {   'description': 'BOH',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet1/0/36': {   'description': 'BOH',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet1/0/37': {   'description': '',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet1/0/38': {   'description': '',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet1/0/39': {   'description': '',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet1/0/4': {   'description': 'VCE2_GE1_WANA',
                                                  'protocol': 'up',
                                                  'status': 'up'},
                      'GigabitEthernet1/0/40': {   'description': '',
                                                   'protocol': 'down',
                                                   'status': 'admin down'},
                      'GigabitEthernet1/0/41': {   'description': 'POS',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet1/0/42': {   'description': 'POS',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet1/0/43': {   'description': 'POS',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet1/0/44': {   'description': 'EBPN',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet1/0/45': {   'description': 'Server',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet1/0/46': {   'description': 'Server',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet1/0/47': {   'description': 'Server',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet1/0/48': {   'description': 'Server',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet1/0/5': {   'description': 'VCE1_SFP2_POLR',
                                                  'protocol': 'up',
                                                  'status': 'up'},
                      'GigabitEthernet1/0/6': {   'description': 'VCE1_SFP1',
                                                  'protocol': 'down',
                                                  'status': 'down'},
                      'GigabitEthernet1/0/7': {   'description': '//RESERVED_VOICE//',
                                                  'protocol': 'down',
                                                  'status': 'down'},
                      'GigabitEthernet1/0/8': {   'description': '//RESERVED_VCE//',
                                                  'protocol': 'down',
                                                  'status': 'down'},
                      'GigabitEthernet1/0/9': {   'description': 'DEMARC_POLR',
                                                  'protocol': 'up',
                                                  'status': 'up'},
                      'GigabitEthernet1/1/1': {   'description': '',
                                                  'protocol': 'down',
                                                  'status': 'down'},
                      'GigabitEthernet1/1/2': {   'description': '',
                                                  'protocol': 'down',
                                                  'status': 'down'},
                      'GigabitEthernet1/1/3': {   'description': '',
                                                  'protocol': 'down',
                                                  'status': 'down'},
                      'GigabitEthernet1/1/4': {   'description': '',
                                                  'protocol': 'down',
                                                  'status': 'down'},
                      'GigabitEthernet2/0/1': {   'description': 'VCE2_LAN3',
                                                  'protocol': 'up',
                                                  'status': 'up'},
                      'GigabitEthernet2/0/10': {   'description': 'DEMARC_WANB',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet2/0/11': {   'description': 'WAP',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet2/0/12': {   'description': 'WAP',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet2/0/13': {   'description': 'WAP',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet2/0/14': {   'description': 'WAP',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet2/0/15': {   'description': 'WAP',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet2/0/16': {   'description': 'WAP',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet2/0/17': {   'description': 'WAP',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet2/0/18': {   'description': 'WAP',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet2/0/19': {   'description': 'WAP',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet2/0/2': {   'description': '//RESERVED_VCE//',
                                                  'protocol': 'down',
                                                  'status': 'admin down'},
                      'GigabitEthernet2/0/20': {   'description': 'WAP',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet2/0/21': {   'description': 'CE_DE',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet2/0/22': {   'description': 'CE_DE_FoH_Mac_Mini',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet2/0/23': {   'description': 'PoE '
                                                                  'Initiatives',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet2/0/24': {   'description': 'VSAM',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet2/0/25': {   'description': 'VSAM',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet2/0/26': {   'description': '',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet2/0/27': {   'description': 'mPOS Wired '
                                                                  'Printer',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet2/0/28': {   'description': 'mPOS Wired '
                                                                  'Printer',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet2/0/29': {   'description': 'Cash Drawer',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet2/0/3': {   'description': 'VCE1_GE2_WANB',
                                                  'protocol': 'up',
                                                  'status': 'up'},
                      'GigabitEthernet2/0/30': {   'description': 'Cash Drawer',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet2/0/31': {   'description': 'Cash Drawer',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet2/0/32': {   'description': 'BOH',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet2/0/33': {   'description': 'BOH',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet2/0/34': {   'description': 'BOH',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet2/0/35': {   'description': 'BOH',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet2/0/36': {   'description': 'BOH',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet2/0/37': {   'description': '',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet2/0/38': {   'description': '',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet2/0/39': {   'description': '',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet2/0/4': {   'description': 'VCE2_GE2_WANB',
                                                  'protocol': 'up',
                                                  'status': 'up'},
                      'GigabitEthernet2/0/40': {   'description': '',
                                                   'protocol': 'down',
                                                   'status': 'admin down'},
                      'GigabitEthernet2/0/41': {   'description': 'POS',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet2/0/42': {   'description': 'POS',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet2/0/43': {   'description': 'POS',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet2/0/44': {   'description': 'EBPN',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet2/0/45': {   'description': 'Server',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet2/0/46': {   'description': 'Server',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet2/0/47': {   'description': 'Server',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet2/0/48': {   'description': 'Server',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet2/0/5': {   'description': 'VCE2_SFP2_POLR',
                                                  'protocol': 'up',
                                                  'status': 'up'},
                      'GigabitEthernet2/0/6': {   'description': 'VCE2_SFP1',
                                                  'protocol': 'down',
                                                  'status': 'down'},
                      'GigabitEthernet2/0/7': {   'description': '//RESERVED_VOICE//',
                                                  'protocol': 'down',
                                                  'status': 'down'},
                      'GigabitEthernet2/0/8': {   'description': '//RESERVED_VCE//',
                                                  'protocol': 'down',
                                                  'status': 'down'},
                      'GigabitEthernet2/0/9': {   'description': 'DEMARC_WANC',
                                                  'protocol': 'down',
                                                  'status': 'down'},
                      'GigabitEthernet2/1/1': {   'description': '',
                                                  'protocol': 'down',
                                                  'status': 'down'},
                      'GigabitEthernet2/1/2': {   'description': '',
                                                  'protocol': 'down',
                                                  'status': 'down'},
                      'GigabitEthernet2/1/3': {   'description': '',
                                                  'protocol': 'down',
                                                  'status': 'down'},
                      'GigabitEthernet2/1/4': {   'description': '',
                                                  'protocol': 'down',
                                                  'status': 'down'},
                      'GigabitEthernet3/0/1': {   'description': 'Self-Checkout_iPAD_04',
                                                  'protocol': 'down',
                                                  'status': 'down'},
                      'GigabitEthernet3/0/10': {   'description': 'WAP',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet3/0/11': {   'description': 'WAP',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet3/0/12': {   'description': 'WAP',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet3/0/13': {   'description': 'WAP',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet3/0/14': {   'description': 'WAP',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet3/0/15': {   'description': 'WAP',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet3/0/16': {   'description': 'WAP',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet3/0/17': {   'description': 'WAP',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet3/0/18': {   'description': 'WAP',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet3/0/19': {   'description': 'WAP',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet3/0/2': {   'description': 'Self-Checkout_Printer_04',
                                                  'protocol': 'down',
                                                  'status': 'down'},
                      'GigabitEthernet3/0/20': {   'description': 'WAP',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet3/0/21': {   'description': 'CE_DE',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet3/0/22': {   'description': 'CE_DE',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet3/0/23': {   'description': 'PoE '
                                                                  'Initiatives',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet3/0/24': {   'description': 'VSAM',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet3/0/25': {   'description': 'VSAM',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet3/0/26': {   'description': 'mPOS Wired '
                                                                  'Printer',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet3/0/27': {   'description': 'mPOS Wired '
                                                                  'Printer',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet3/0/28': {   'description': 'mPOS Wired '
                                                                  'Printer',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet3/0/29': {   'description': 'Cash Drawer',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet3/0/3': {   'description': 'Self-Checkout_Payment-Terminal_04',
                                                  'protocol': 'down',
                                                  'status': 'down'},
                      'GigabitEthernet3/0/30': {   'description': 'Cash Drawer',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet3/0/31': {   'description': 'Cash Drawer',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet3/0/32': {   'description': 'BOH',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet3/0/33': {   'description': 'BOH',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet3/0/34': {   'description': 'BOH',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet3/0/35': {   'description': 'BOH',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet3/0/36': {   'description': 'BOH',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet3/0/37': {   'description': '',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet3/0/38': {   'description': '',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet3/0/39': {   'description': '',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet3/0/4': {   'description': 'Self-Checkout_Reserved_04',
                                                  'protocol': 'down',
                                                  'status': 'down'},
                      'GigabitEthernet3/0/40': {   'description': '',
                                                   'protocol': 'down',
                                                   'status': 'admin down'},
                      'GigabitEthernet3/0/41': {   'description': 'POS',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet3/0/42': {   'description': 'POS',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet3/0/43': {   'description': 'POS',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet3/0/44': {   'description': 'EBPN',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet3/0/45': {   'description': 'Server',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet3/0/46': {   'description': 'Server',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet3/0/47': {   'description': 'Server',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                      'GigabitEthernet3/0/48': {   'description': 'Server',
                                                   'protocol': 'up',
                                                   'status': 'up'},
                      'GigabitEthernet3/0/5': {   'description': 'WAP',
                                                  'protocol': 'down',
                                                  'status': 'down'},
                      'GigabitEthernet3/0/6': {   'description': 'WAP',
                                                  'protocol': 'down',
                                                  'status': 'down'},
                      'GigabitEthernet3/0/7': {   'description': 'WAP',
                                                  'protocol': 'down',
                                                  'status': 'down'},
                      'GigabitEthernet3/0/8': {   'description': 'WAP',
                                                  'protocol': 'down',
                                                  'status': 'down'},
                      'GigabitEthernet3/0/9': {   'description': 'WAP',
                                                  'protocol': 'down',
                                                  'status': 'down'},
                      'GigabitEthernet3/1/1': {   'description': '',
                                                  'protocol': 'down',
                                                  'status': 'down'},
                      'GigabitEthernet3/1/2': {   'description': '',
                                                  'protocol': 'down',
                                                  'status': 'down'},
                      'GigabitEthernet3/1/3': {   'description': '',
                                                  'protocol': 'down',
                                                  'status': 'down'},
                      'GigabitEthernet3/1/4': {   'description': '',
                                                  'protocol': 'down',
                                                  'status': 'down'},
                      'Loopback0': {   'description': '',
                                       'protocol': 'up',
                                       'status': 'up'},
                      'TenGigabitEthernet1/1/1': {   'description': '',
                                                     'protocol': 'down',
                                                     'status': 'down'},
                      'TenGigabitEthernet1/1/2': {   'description': '',
                                                     'protocol': 'down',
                                                     'status': 'down'},
                      'TenGigabitEthernet1/1/3': {   'description': '',
                                                     'protocol': 'down',
                                                     'status': 'down'},
                      'TenGigabitEthernet1/1/4': {   'description': '',
                                                     'protocol': 'down',
                                                     'status': 'down'},
                      'TenGigabitEthernet1/1/5': {   'description': '',
                                                     'protocol': 'down',
                                                     'status': 'down'},
                      'TenGigabitEthernet1/1/6': {   'description': '',
                                                     'protocol': 'down',
                                                     'status': 'down'},
                      'TenGigabitEthernet1/1/7': {   'description': '',
                                                     'protocol': 'down',
                                                     'status': 'down'},
                      'TenGigabitEthernet1/1/8': {   'description': '',
                                                     'protocol': 'down',
                                                     'status': 'down'},
                      'TenGigabitEthernet2/1/1': {   'description': '',
                                                     'protocol': 'down',
                                                     'status': 'down'},
                      'TenGigabitEthernet2/1/2': {   'description': '',
                                                     'protocol': 'down',
                                                     'status': 'down'},
                      'TenGigabitEthernet2/1/3': {   'description': '',
                                                     'protocol': 'down',
                                                     'status': 'down'},
                      'TenGigabitEthernet2/1/4': {   'description': '',
                                                     'protocol': 'down',
                                                     'status': 'down'},
                      'TenGigabitEthernet2/1/5': {   'description': '',
                                                     'protocol': 'down',
                                                     'status': 'down'},
                      'TenGigabitEthernet2/1/6': {   'description': '',
                                                     'protocol': 'down',
                                                     'status': 'down'},
                      'TenGigabitEthernet2/1/7': {   'description': '',
                                                     'protocol': 'down',
                                                     'status': 'down'},
                      'TenGigabitEthernet2/1/8': {   'description': '',
                                                     'protocol': 'down',
                                                     'status': 'down'},
                      'TenGigabitEthernet3/1/1': {   'description': '',
                                                     'protocol': 'down',
                                                     'status': 'down'},
                      'TenGigabitEthernet3/1/2': {   'description': '',
                                                     'protocol': 'down',
                                                     'status': 'down'},
                      'TenGigabitEthernet3/1/3': {   'description': '',
                                                     'protocol': 'down',
                                                     'status': 'down'},
                      'TenGigabitEthernet3/1/4': {   'description': '',
                                                     'protocol': 'down',
                                                     'status': 'down'},
                      'TenGigabitEthernet3/1/5': {   'description': '',
                                                     'protocol': 'down',
                                                     'status': 'down'},
                      'TenGigabitEthernet3/1/6': {   'description': '',
                                                     'protocol': 'down',
                                                     'status': 'down'},
                      'TenGigabitEthernet3/1/7': {   'description': '',
                                                     'protocol': 'down',
                                                     'status': 'down'},
                      'TenGigabitEthernet3/1/8': {   'description': '',
                                                     'protocol': 'down',
                                                     'status': 'down'},
                      'TwentyFiveGigE1/1/1': {   'description': '',
                                                 'protocol': 'down',
                                                 'status': 'down'},
                      'TwentyFiveGigE1/1/2': {   'description': '',
                                                 'protocol': 'down',
                                                 'status': 'down'},
                      'TwentyFiveGigE2/1/1': {   'description': '',
                                                 'protocol': 'down',
                                                 'status': 'down'},
                      'TwentyFiveGigE2/1/2': {   'description': '',
                                                 'protocol': 'down',
                                                 'status': 'down'},
                      'TwentyFiveGigE3/1/1': {   'description': '',
                                                 'protocol': 'down',
                                                 'status': 'down'},
                      'TwentyFiveGigE3/1/2': {   'description': '',
                                                 'protocol': 'down',
                                                 'status': 'down'},
                      'Vlan1': {   'description': '',
                                   'protocol': 'down',
                                   'status': 'admin down'},
                      'Vlan7': {   'description': '',
                                   'protocol': 'up',
                                   'status': 'up'}}}